credentials       = "credentials.json"
name              = "myvm1"
gcp_project       = "empyrean-app-408116"
region            = "us-central1"
zone              = "us-central1-a"
subnet_cidr_range = "10.0.0.0/16"
